# Broadcasting

In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0], 
            [1.2, 104.0, 52.0, 8.0], 
            [1.8, 135.0, 99.0, 0.9]])

In [2]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


axis = 0 意思是垂直求和, axis = 1 意思是水平求和。

In [ ]:
percentage = 100 * A / (cal.reshape(1, 4))  # python广播机制 (broadcasting)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# A note on python/numpy vectors

不应该采取形如 (5, ) 来构造向量，而应该使用 (5,1)  
错误做法：

In [ ]:
a = np.random.randn(5)  # rand生成均匀分布的随机数，randn生成正态分布的随机数
print(a)

[0.52950781 0.69013777 0.94308893 0.76357242 0.14623756]


In [11]:
print(a.shape)

(5,)


这就是被称为"rand one array"的特殊数据结构  
它的行为既不像行向量也不像列向量  
DO NOT USE IT

In [12]:
print(a.T)

[0.52950781 0.69013777 0.94308893 0.76357242 0.14623756]


In [13]:
print(a.T.shape)

(5,)


In [14]:
print(np.dot(a,a.T))

2.250513645453466


正确用法如下：

In [15]:
b = np.random.randn(5,1)
print(b)

[[-0.49435647]
 [-0.4904409 ]
 [ 0.10485254]
 [-0.80933526]
 [-1.00154576]]


In [16]:
print(b.shape)

(5, 1)


In [17]:
print(b.T)

[[-0.49435647 -0.4904409   0.10485254 -0.80933526 -1.00154576]]


In [18]:
print(np.dot(b,b.T))

[[ 0.24438832  0.24245263 -0.05183453  0.40010012  0.49512062]
 [ 0.24245263  0.24053228 -0.05142397  0.39693112  0.49119901]
 [-0.05183453 -0.05142397  0.01099405 -0.08486086 -0.10501462]
 [ 0.40010012  0.39693112 -0.08486086  0.65502357  0.8105863 ]
 [ 0.49512062  0.49119901 -0.10501462  0.8105863   1.00309392]]


可以使用“断言”语句确保不出现rand one array

In [22]:
assert(a.shape == (5,1))

AssertionError: 

In [23]:
assert(b.shape == (5,1))